import type { ModuleCatalogItem, ModuleCategory } from '@/types/builder';

type ModuleSeed = {
  key: string;
  label: string;
  category: ModuleCategory;
  monthlyPrice: number;
  audienceFit: string;
  implementationComplexity: 'low' | 'medium' | 'high';
  purpose: string;
  churchBenefit: string;
};

const moduleSeeds: ModuleSeed[] = [
  { key: 'care_pastoral_rounds', label: 'Pastoral Care Rounds', category: 'Care', monthlyPrice: 49, audienceFit: 'Pastors and care teams', implementationComplexity: 'low', purpose: 'Organizes recurring care touchpoints for members who need weekly follow-up and creates assignment queues for staff and trained volunteers.', churchBenefit: 'Prevents vulnerable members from falling through cracks, improves pastoral consistency, and gives leadership confidence that every care promise is being kept.' },
  { key: 'care_bereavement_pathways', label: 'Bereavement Support Pathways', category: 'Care', monthlyPrice: 39, audienceFit: 'Care ministers and grief teams', implementationComplexity: 'medium', purpose: 'Automates a 12-week care sequence for grieving households, including check-ins, prayer prompts, and milestone follow-up reminders.', churchBenefit: 'Helps grieving families feel continuously shepherded during difficult seasons and strengthens trust in the church’s long-term care ministry.' },
  { key: 'care_hospital_followup', label: 'Hospital Discharge Follow-up', category: 'Care', monthlyPrice: 59, audienceFit: 'Deacon and visitation teams', implementationComplexity: 'medium', purpose: 'Triggers immediate and scheduled outreach after hospitalization with medication, meal train, and transportation follow-up tasks.', churchBenefit: 'Reduces preventable crises after discharge and ensures families receive practical and spiritual support exactly when they need it.' },
  { key: 'care_prayer_triage', label: 'Prayer Request Triage Queue', category: 'Care', monthlyPrice: 45, audienceFit: 'Prayer coordinators', implementationComplexity: 'low', purpose: 'Routes incoming prayer requests by urgency, theme, and confidentiality level while logging response ownership and completion.', churchBenefit: 'Increases prayer response speed, protects sensitive requests, and gives congregants confidence their requests are personally seen and covered.' },
  { key: 'care_crisis_response', label: 'Crisis Response Coordination', category: 'Care', monthlyPrice: 79, audienceFit: 'Senior leadership and crisis teams', implementationComplexity: 'high', purpose: 'Provides incident-command style workflows for urgent family, health, or safety events with escalation stages and accountability logs.', churchBenefit: 'Enables calm, unified action during emergencies and protects leadership from communication gaps during high-pressure situations.' },
  { key: 'care_homebound_support', label: 'Homebound Member Care Plans', category: 'Care', monthlyPrice: 42, audienceFit: 'Care managers and volunteers', implementationComplexity: 'medium', purpose: 'Builds durable care plans for homebound members with cadence-based check-ins, fallback contacts, and special accommodation notes.', churchBenefit: 'Creates dependable connection for isolated members and gives families peace of mind that someone is consistently checking in.' },

  { key: 'safety_daily_checkin', label: 'Daily Safety Check-in', category: 'Safety', monthlyPrice: 59, audienceFit: 'Senior and assisted-living ministries', implementationComplexity: 'low', purpose: 'Sends scheduled SMS or voice prompts and tracks confirmations, misses, and time-to-response for each monitored member.', churchBenefit: 'Identifies potential safety concerns early and gives ministries real-time visibility into who may require immediate follow-up.' },
  { key: 'safety_fall_risk_alerts', label: 'Fall Risk Alert Workflow', category: 'Safety', monthlyPrice: 54, audienceFit: 'Elder care coordinators', implementationComplexity: 'medium', purpose: 'Adds specialized escalation ladders for suspected fall events, including caregiver calls, welfare checks, and urgent pastor notifications.', churchBenefit: 'Shortens response time for high-risk seniors and reduces the chance that serious incidents go unnoticed.' },
  { key: 'safety_medication_prompts', label: 'Medication Reminder Assurance', category: 'Safety', monthlyPrice: 64, audienceFit: 'Health-focused care teams', implementationComplexity: 'medium', purpose: 'Manages reminder windows, confirmations, and missed-dose exceptions with clear handoffs to assigned caregivers.', churchBenefit: 'Supports healthier daily rhythms for members while equipping caregivers with transparent adherence trends.' },
  { key: 'safety_weather_welfare', label: 'Severe Weather Welfare Checks', category: 'Safety', monthlyPrice: 35, audienceFit: 'Community response ministries', implementationComplexity: 'low', purpose: 'Launches targeted outreach campaigns during storms or heat waves for members in affected ZIP codes with rapid status collection.', churchBenefit: 'Helps churches proactively protect vulnerable households and coordinate volunteers before conditions worsen.' },
  { key: 'safety_emergency_hotline', label: 'Emergency Care Hotline Routing', category: 'Safety', monthlyPrice: 69, audienceFit: 'Large multi-staff churches', implementationComplexity: 'high', purpose: 'Creates structured intake and triage workflows for urgent care calls with after-hours handoff and acknowledgement tracking.', churchBenefit: 'Ensures urgent calls are never lost and that families always reach the right responder quickly.' },
  { key: 'safety_guardian_notifications', label: 'Guardian Notification Matrix', category: 'Safety', monthlyPrice: 44, audienceFit: 'Family ministries and elder care', implementationComplexity: 'medium', purpose: 'Defines priority guardian/contact trees for each member and triggers notifications in ordered escalation sequences.', churchBenefit: 'Keeps the right family contacts informed promptly while reducing confusion during high-stress events.' },

  { key: 'engagement_absence_recovery', label: 'Absence Recovery Journey', category: 'Engagement', monthlyPrice: 46, audienceFit: 'Assimilation and shepherding teams', implementationComplexity: 'medium', purpose: 'Detects attendance drop-off patterns and starts personalized reconnect workflows with call, text, and visit tasks.', churchBenefit: 'Improves retention by helping staff and volunteers reconnect lovingly before absence turns into disengagement.' },
  { key: 'engagement_first_time_path', label: 'First-Time Guest Shepherding', category: 'Engagement', monthlyPrice: 39, audienceFit: 'Guest experience teams', implementationComplexity: 'low', purpose: 'Guides a 30-day follow-up process for new guests with segmented communications based on family profile and interest.', churchBenefit: 'Converts more first-time guests into returning participants and creates warmer first impressions of church care.' },
  { key: 'engagement_small_group_match', label: 'Small Group Matching Assistant', category: 'Engagement', monthlyPrice: 52, audienceFit: 'Discipleship pastors', implementationComplexity: 'medium', purpose: 'Matches people into groups based on geography, life stage, and availability while managing overflow and waitlists.', churchBenefit: 'Accelerates belonging and increases long-term spiritual engagement through better group placement.' },
  { key: 'engagement_volunteer_reengage', label: 'Volunteer Re-engagement Campaigns', category: 'Engagement', monthlyPrice: 37, audienceFit: 'Volunteer directors', implementationComplexity: 'low', purpose: 'Automatically re-invites inactive volunteers with contextual ministry opportunities and follow-up nudges.', churchBenefit: 'Recovers dormant serving capacity and prevents ministry burnout on active volunteers.' },
  { key: 'engagement_prayer_testimony', label: 'Prayer & Testimony Follow-through', category: 'Engagement', monthlyPrice: 33, audienceFit: 'Prayer and worship teams', implementationComplexity: 'low', purpose: 'Tracks answered-prayer and testimony follow-up loops to celebrate outcomes and deepen congregational encouragement.', churchBenefit: 'Strengthens congregational faith culture by turning prayer moments into ongoing discipleship stories.' },
  { key: 'engagement_baptism_pipeline', label: 'Baptism Preparation Pipeline', category: 'Engagement', monthlyPrice: 43, audienceFit: 'Next steps teams', implementationComplexity: 'medium', purpose: 'Orchestrates class registration, mentor assignment, reminders, and pastoral confirmations for baptism candidates.', churchBenefit: 'Improves completion rates for key spiritual milestones and reduces administrative friction for staff.' },

  { key: 'ops_case_management', label: 'Care Case Management Workspace', category: 'Operations', monthlyPrice: 84, audienceFit: 'Care directors and administrators', implementationComplexity: 'high', purpose: 'Provides structured case records with notes, tasks, SLAs, and escalation audit trails for complex care situations.', churchBenefit: 'Centralizes institutional memory, improves accountability, and supports continuity during staff transitions.' },
  { key: 'ops_shift_handoffs', label: 'Volunteer Shift Handoff Logs', category: 'Operations', monthlyPrice: 36, audienceFit: 'Volunteer coordinators', implementationComplexity: 'low', purpose: 'Captures context-rich handoff notes between volunteer shifts and flags unresolved needs for next responders.', churchBenefit: 'Reduces dropped tasks and keeps ministry service quality consistent across changing volunteer schedules.' },
  { key: 'ops_ministry_sla', label: 'Ministry SLA Tracker', category: 'Operations', monthlyPrice: 47, audienceFit: 'Operations leaders', implementationComplexity: 'medium', purpose: 'Measures response commitments for outreach, follow-up, and incident handling against configurable service targets.', churchBenefit: 'Creates operational discipline and surfaces bottlenecks before they become trust-damaging delays.' },
  { key: 'ops_event_care_planning', label: 'Event Care Coverage Planner', category: 'Operations', monthlyPrice: 41, audienceFit: 'Weekend operations teams', implementationComplexity: 'medium', purpose: 'Plans care coverage for services and events, assigning responders by role, skill, and availability windows.', churchBenefit: 'Improves readiness for high-attendance weekends and prevents care blind spots during major events.' },
  { key: 'ops_transport_coordination', label: 'Compassion Transport Coordination', category: 'Operations', monthlyPrice: 34, audienceFit: 'Mercy ministries', implementationComplexity: 'low', purpose: 'Coordinates rides for medical appointments, worship attendance, and recovery meetings with volunteer dispatch visibility.', churchBenefit: 'Expands accessibility for members with mobility barriers and reinforces practical care ministry impact.' },
  { key: 'ops_meal_train_orchestrator', label: 'Meal Train Orchestrator', category: 'Operations', monthlyPrice: 31, audienceFit: 'Family care teams', implementationComplexity: 'low', purpose: 'Automates meal request scheduling, volunteer signups, dietary notes, and reminder coordination.', churchBenefit: 'Simplifies compassionate response after illness or birth while increasing volunteer participation.' },

  { key: 'intel_risk_scoring', label: 'Member Risk Scoring', category: 'Intelligence', monthlyPrice: 72, audienceFit: 'Care analysts and pastors', implementationComplexity: 'medium', purpose: 'Calculates explainable risk using missed check-ins, escalation history, and response behavior trends.', churchBenefit: 'Helps leaders prioritize care attention with defensible data instead of intuition alone.' },
  { key: 'intel_response_insights', label: 'Response Time Insights', category: 'Intelligence', monthlyPrice: 48, audienceFit: 'Operations analysts', implementationComplexity: 'low', purpose: 'Breaks down average response times by team, ministry, and escalation stage to reveal performance gaps.', churchBenefit: 'Empowers staff coaching and process changes that improve responsiveness and member trust.' },
  { key: 'intel_care_load_balance', label: 'Care Load Balancing', category: 'Intelligence', monthlyPrice: 57, audienceFit: 'Care managers', implementationComplexity: 'medium', purpose: 'Analyzes active case volume and task burden across caregivers, recommending balanced reassignment options.', churchBenefit: 'Protects team health, prevents burnout, and keeps care quality high even as demand grows.' },
  { key: 'intel_dropoff_detection', label: 'Spiritual Drop-off Detection', category: 'Intelligence', monthlyPrice: 63, audienceFit: 'Discipleship leadership', implementationComplexity: 'medium', purpose: 'Detects attendance, serving, and engagement decline patterns and highlights at-risk members for outreach.', churchBenefit: 'Supports earlier pastoral intervention and helps preserve long-term discipleship momentum.' },
  { key: 'intel_prayer_trend_map', label: 'Prayer Trend Mapping', category: 'Intelligence', monthlyPrice: 29, audienceFit: 'Prayer directors', implementationComplexity: 'low', purpose: 'Groups prayer requests into trend themes over time to inform teaching focus and care campaign planning.', churchBenefit: 'Turns prayer data into ministry insight, aligning church response with real congregational needs.' },
  { key: 'intel_referral_performance', label: 'Referral Performance Analytics', category: 'Intelligence', monthlyPrice: 38, audienceFit: 'Growth and outreach teams', implementationComplexity: 'low', purpose: 'Tracks referral source, conversion, and downstream engagement to evaluate community growth channels.', churchBenefit: 'Improves outreach ROI and clarifies which invitation pathways produce lasting church involvement.' },

  { key: 'recovery_addiction_pathway', label: 'Addiction Recovery Journey', category: 'Recovery', monthlyPrice: 66, audienceFit: 'Recovery ministries', implementationComplexity: 'high', purpose: 'Provides milestone-driven recovery plans with sponsor check-ins, missed meeting alerts, and relapse response workflows.', churchBenefit: 'Creates compassionate accountability that supports sustained recovery and long-term community restoration.' },
  { key: 'recovery_postop_monitoring', label: 'Post-Op Recovery Monitoring', category: 'Recovery', monthlyPrice: 58, audienceFit: 'Health support ministries', implementationComplexity: 'medium', purpose: 'Schedules symptom check-ins, medication confirmations, and caregiver escalations during post-surgery windows.', churchBenefit: 'Improves post-op safety and gives families practical support during medically vulnerable periods.' },
  { key: 'recovery_grief_support', label: 'Extended Grief Support Cadence', category: 'Recovery', monthlyPrice: 44, audienceFit: 'Counseling and care teams', implementationComplexity: 'medium', purpose: 'Sustains long-tail support for grieving individuals with timed encouragement and counselor referral steps.', churchBenefit: 'Reduces emotional isolation after initial support drops off and reflects the church’s long-term compassion.' },
  { key: 'recovery_financial_crisis', label: 'Financial Crisis Recovery Plan', category: 'Recovery', monthlyPrice: 51, audienceFit: 'Benevolence ministries', implementationComplexity: 'medium', purpose: 'Coordinates benevolence requests, coaching referrals, and accountability follow-up for households in economic distress.', churchBenefit: 'Moves families from emergency assistance toward sustainable stability while stewarding church resources wisely.' },
  { key: 'recovery_family_reconciliation', label: 'Family Reconciliation Workflow', category: 'Recovery', monthlyPrice: 42, audienceFit: 'Pastoral counseling teams', implementationComplexity: 'high', purpose: 'Supports structured reconciliation processes with milestones, mediator notes, and follow-up check-in checkpoints.', churchBenefit: 'Improves relational healing outcomes through consistent pastoral process and thoughtful next-step guidance.' },
  { key: 'recovery_reentry_support', label: 'Re-entry Support Program', category: 'Recovery', monthlyPrice: 62, audienceFit: 'Justice and mercy ministries', implementationComplexity: 'high', purpose: 'Guides returning citizens through housing, job, mentorship, and spiritual care milestones with coordinated team tasks.', churchBenefit: 'Helps vulnerable members rebuild stable lives and strengthens the church’s community restoration impact.' },

  { key: 'volunteer_oncall_rotations', label: 'On-Call Rotation Manager', category: 'Volunteer Coordination', monthlyPrice: 36, audienceFit: 'Volunteer schedulers', implementationComplexity: 'low', purpose: 'Creates fair on-call rotations, reminder notifications, and backup assignment logic for care response teams.', churchBenefit: 'Ensures reliable coverage without overburdening a small set of faithful volunteers.' },
  { key: 'volunteer_skill_matching', label: 'Volunteer Skill Matching', category: 'Volunteer Coordination', monthlyPrice: 43, audienceFit: 'Ministry operations', implementationComplexity: 'medium', purpose: 'Matches care tasks with volunteer competencies, certifications, and comfort levels to improve fit and outcomes.', churchBenefit: 'Raises care quality and volunteer confidence by aligning people with roles where they can thrive.' },
  { key: 'volunteer_retention_signals', label: 'Volunteer Retention Signals', category: 'Volunteer Coordination', monthlyPrice: 32, audienceFit: 'Volunteer directors', implementationComplexity: 'low', purpose: 'Monitors serving cadence changes and predicts disengagement risk with timely retention prompts for leaders.', churchBenefit: 'Protects volunteer continuity and reduces churn that can destabilize ministry programs.' },
  { key: 'volunteer_background_compliance', label: 'Background Check Compliance', category: 'Volunteer Coordination', monthlyPrice: 55, audienceFit: 'Family and safety ministries', implementationComplexity: 'medium', purpose: 'Tracks screenings, expiration reminders, and role eligibility compliance for volunteers serving vulnerable groups.', churchBenefit: 'Strengthens child and vulnerable adult safety practices while reducing compliance administration overhead.' },
  { key: 'volunteer_training_paths', label: 'Volunteer Training Paths', category: 'Volunteer Coordination', monthlyPrice: 34, audienceFit: 'Training coordinators', implementationComplexity: 'low', purpose: 'Assigns training sequences by ministry role and validates completion before activating higher-trust responsibilities.', churchBenefit: 'Improves ministry readiness and safety by ensuring volunteers are equipped before serving in sensitive contexts.' },
  { key: 'volunteer_appreciation_cycles', label: 'Volunteer Appreciation Cycles', category: 'Volunteer Coordination', monthlyPrice: 26, audienceFit: 'Volunteer care teams', implementationComplexity: 'low', purpose: 'Schedules appreciation touchpoints and personalized recognition reminders based on service milestones.', churchBenefit: 'Builds healthier volunteer culture and reinforces long-term commitment through intentional encouragement.' },

  { key: 'comm_multichannel_outreach', label: 'Multi-channel Outreach Engine', category: 'Communication', monthlyPrice: 61, audienceFit: 'Communications teams', implementationComplexity: 'medium', purpose: 'Coordinates SMS, voice, and email campaigns with audience segmentation and response tracking in one workspace.', churchBenefit: 'Increases message reach and clarity while reducing fragmented communication across disconnected tools.' },
  { key: 'comm_care_announcements', label: 'Care Announcement Broadcasts', category: 'Communication', monthlyPrice: 28, audienceFit: 'Pastoral communication staff', implementationComplexity: 'low', purpose: 'Delivers targeted care updates and prayer mobilization notices to selected teams and response circles.', churchBenefit: 'Mobilizes the right people quickly when urgent congregational care needs arise.' },
  { key: 'comm_language_adaptation', label: 'Language Adaptation Assistant', category: 'Communication', monthlyPrice: 40, audienceFit: 'Multilingual congregations', implementationComplexity: 'medium', purpose: 'Adapts care communications into preferred languages and readability levels for diverse congregational segments.', churchBenefit: 'Improves inclusion and comprehension so more families can fully engage with care communications.' },
  { key: 'comm_voice_broadcast', label: 'Voice Broadcast Outreach', category: 'Communication', monthlyPrice: 46, audienceFit: 'Senior-focused ministries', implementationComplexity: 'low', purpose: 'Enables recorded or generated voice updates for members less likely to respond to text-based communication.', churchBenefit: 'Increases reach among older or low-tech members and improves equitable access to church updates.' },
  { key: 'comm_prayer_chain_coord', label: 'Prayer Chain Coordination', category: 'Communication', monthlyPrice: 24, audienceFit: 'Prayer chain leaders', implementationComplexity: 'low', purpose: 'Automates prayer chain circulation with urgency flags, confidentiality controls, and completion visibility.', churchBenefit: 'Accelerates prayer mobilization while preserving pastoral discretion for sensitive requests.' },
  { key: 'comm_followup_sequences', label: 'Follow-up Sequence Builder', category: 'Communication', monthlyPrice: 49, audienceFit: 'Assimilation and care teams', implementationComplexity: 'medium', purpose: 'Designs branching follow-up journeys for guests, absent members, and care cases with measured engagement outcomes.', churchBenefit: 'Improves consistency and effectiveness of outreach by replacing ad-hoc manual follow-up.' },

  { key: 'analytics_ministry_kpis', label: 'Ministry KPI Scoreboard', category: 'Analytics', monthlyPrice: 58, audienceFit: 'Executive pastors and ops leaders', implementationComplexity: 'medium', purpose: 'Tracks core care metrics including response rate, incident burden, and case resolution velocity in one executive view.', churchBenefit: 'Supports faster leadership decisions with trustworthy operational visibility across ministries.' },
  { key: 'analytics_escalation_funnel', label: 'Escalation Funnel Analytics', category: 'Analytics', monthlyPrice: 47, audienceFit: 'Care operations managers', implementationComplexity: 'medium', purpose: 'Visualizes escalation movement from first miss to resolution with stage-by-stage dropout and delay analysis.', churchBenefit: 'Helps teams pinpoint where care workflows stall so they can improve safety outcomes quickly.' },
  { key: 'analytics_member_health', label: 'Member Health Trendboards', category: 'Analytics', monthlyPrice: 53, audienceFit: 'Pastoral and wellness ministries', implementationComplexity: 'medium', purpose: 'Aggregates longitudinal trends in check-ins, concerns, and care interventions for each member cohort.', churchBenefit: 'Reveals emerging needs earlier and improves strategic care planning for the congregation.' },
  { key: 'analytics_volunteer_capacity', label: 'Volunteer Capacity Analytics', category: 'Analytics', monthlyPrice: 35, audienceFit: 'Volunteer operations', implementationComplexity: 'low', purpose: 'Shows serving load, open shifts, and response performance by volunteer segment and ministry team.', churchBenefit: 'Enables proactive staffing decisions and protects ministries from chronic volunteer shortages.' },
  { key: 'analytics_referral_leaderboard', label: 'Referral Leaderboard & Rewards', category: 'Analytics', monthlyPrice: 31, audienceFit: 'Growth and outreach leaders', implementationComplexity: 'low', purpose: 'Tracks referral performance, conversion totals, and incentive thresholds such as free month and premium onboarding flags.', churchBenefit: 'Encourages mission-aligned growth through transparent recognition and measurable referral outcomes.' },
  { key: 'analytics_exec_digest', label: 'Executive Weekly Digest', category: 'Analytics', monthlyPrice: 27, audienceFit: 'Senior leadership teams', implementationComplexity: 'low', purpose: 'Compiles weekly snapshots of care health, risk shifts, and unresolved incidents into a concise leadership digest.', churchBenefit: 'Keeps senior leaders aligned on ministry health without requiring constant dashboard deep dives.' },
];

export const moduleCatalog: ModuleCatalogItem[] = moduleSeeds.map((seed) => ({
  key: seed.key,
  label: seed.label,
  category: seed.category,
  monthlyPrice: seed.monthlyPrice,
  audienceFit: seed.audienceFit,
  implementationComplexity: seed.implementationComplexity,
  description: `${seed.purpose} ${seed.churchBenefit}`,
  outcome: seed.churchBenefit,
}));

export function calculateMonthlyPrice(selectedModules: string[]) {
  const selected = moduleCatalog.filter((m) => selectedModules.includes(m.key));
  const subtotal = selected.reduce((sum, m) => sum + m.monthlyPrice, 0);
  const platformBase = 199;
  return {
    subtotal,
    platformBase,
    total: subtotal + platformBase,
  };
}

export function suggestTier(moduleCount: number): 'starter' | 'growth' | 'enterprise' {
  if (moduleCount <= 10) return 'starter';
  if (moduleCount <= 25) return 'growth';
  return 'enterprise';
}
