import { requestRecommendationsFromOpenAI } from "@/lib/openai";

export type RecommendationInput = {
  attendeeCount: number;
  hasCareTeam: boolean;
  needsIncidentTracking: boolean;
  needsAutomations: boolean;
  selectedModules: string[];
};

export type RecommendationItem = {
  key: string;
  reasoning: string;
  priority: "high" | "medium" | "low";
};

export type RecommendationResult = {
  recommendedModules: RecommendationItem[];
  summary: string;
  source: "openai" | "fallback";
};

function fallbackRecommendations(input: RecommendationInput): RecommendationResult {
  const suggestions: RecommendationItem[] = [];

  if (!input.selectedModules.includes("lifesignal_core")) {
    suggestions.push({
      key: "lifesignal_core",
      reasoning: "Core monitoring and response capture is foundational for every deployment.",
      priority: "high",
    });
  }

  if (input.needsIncidentTracking && !input.selectedModules.includes("incident_center")) {
    suggestions.push({
      key: "incident_center",
      reasoning: "Incident tracking was requested in your assessment, so this closes response loops.",
      priority: "high",
    });
  }

  if (input.needsAutomations && !input.selectedModules.includes("escalation_workflows")) {
    suggestions.push({
      key: "escalation_workflows",
      reasoning: "Automation needs map directly to escalation and acknowledgment workflows.",
      priority: "medium",
    });
  }

  if (input.attendeeCount >= 100 && !input.selectedModules.includes("analytics_pack")) {
    suggestions.push({
      key: "analytics_pack",
      reasoning: "Larger cohorts benefit from trend visibility and risk dashboards.",
      priority: "medium",
    });
  }

  if (input.hasCareTeam && !input.selectedModules.includes("team_collaboration")) {
    suggestions.push({
      key: "team_collaboration",
      reasoning: "Your care team can collaborate faster with role-based assignments.",
      priority: "low",
    });
  }

  return {
    recommendedModules: suggestions.slice(0, 5),
    summary:
      suggestions.length === 0
        ? "Current module selection already aligns with your needs assessment."
        : "Recommendations generated from Builder fallback rules.",
    source: "fallback",
  };
}

export async function generateRecommendations(input: RecommendationInput): Promise<RecommendationResult> {
  const fallback = fallbackRecommendations(input);

  try {
    const aiResponse = await requestRecommendationsFromOpenAI(input);

    const normalized: RecommendationItem[] = aiResponse.recommendedModules
      .filter((item) => typeof item?.key === "string" && item.key.length > 0)
      .map((item) => ({
        key: item.key,
        reasoning: typeof item.reasoning === "string" ? item.reasoning : "Recommended based on your assessment.",
        priority:
          item.priority === "high" || item.priority === "medium" || item.priority === "low"
            ? item.priority
            : "medium",
      }));

    if (normalized.length === 0) {
      return fallback;
    }

    return {
      recommendedModules: normalized,
      summary: aiResponse.summary || "Recommendations generated by AI.",
      source: "openai",
    };
  } catch {
    return fallback;
  }
}
